import createConstants from 'utils/create-constants'

const FORCE_REMOTE = false

export const getAPI = function() {
  return !FORCE_REMOTE && process.env.NODE_ENV === 'development' ? 'http://l:9091' : 'http://io-api.3nit.io'
}

export const constants = {
  ...createConstants(
    'LOGGED_IN',
    'LOG_OUT',
    'FETCH_PROFILE_START',
    'FETCH_PROFILE_COMPLETE',
    'LOG_IN',
    'LOG_IN_START',
    'LOG_IN_FAILED',

    'REGISTER_START',
    'REGISTER_COMPLETE',
    'REGISTER_FAILED',

    'UPDATE_PROFILE_START',
    'UPDATE_PROFILE_COMPLETE',

    'FORGOT_START',
    'FORGOT_COMPLETE',

    'FETCH_LANE_START',
    'FETCH_LANE_COMPLETE',

    'FETCH_USER_INQUIRY_START',
    'FETCH_USER_INQUIRY_COMPLETE',
    'FETCH_INQUIRY_ATTRIBUTES',
    'FETCH_INQUIRIES_START',
    'FETCH_INQUIRIES_COMPLETE',
    'FETCH_INQUIRY_ATTRIBUTES',
    'FETCH_INQUIRY_START',
    'FETCH_INQUIRY_COMPLETE',
    'CLEAR_INQUIRY',
    'REMOVE_ORDER_ITEM',
    'ADD_ORDER_ITEM',

    'FETCH_INQUIRY_FORM_VALUE',
    'SET_INQUIRY_FORM_VALUE',
    'CREATE_INQUIRY_START',
    'CREATE_INQUIRY_COMPLETE',
    'UPDATE_INQUIRY_START',
    'UPDATE_INQUIRY_COMPLETE',
    'UPDATE_STEP_START',
    'UPDATE_STEP_COMPLETE',
    'ADD_INQUIRY_COMMENT_START',
    'ADD_INQUIRY_COMMENT_COMPLETE',
    'REMOVE_INQUIRY_COMMENT_START',
    'REMOVE_INQUIRY_COMMENT_COMPLETE',

    'UPDATE_REQUEST',
    'CLEAR_REQUEST',
    'CREATE_ORDER_START',
    'CREATE_ORDER_COMPLETE',
    'UPDATE_ORDER_START',
    'UPDATE_ORDER_COMPLETE',
    'UPDATE_ORDER_ATTRIBUTES_START',
    'UPDATE_ORDER_ATTRIBUTES_COMPLETE',

    'FETCH_USER_START',
    'FETCH_USER_COMPLETE',
    'FETCH_USERS_START',
    'FETCH_USERS_COMPLETE',
    'FETCH_USER_ATTRIBUTES',
    'FETCH_USER_CATEGORIES',
    'CLEAR_USER',
    'FETCH_USER_FORM_VALUE',
    'SET_USER_FORM_VALUE',
    'CREATE_USER_START',
    'CREATE_USER_COMPLETE',
    'UPDATE_USER_START',
    'UPDATE_USER_COMPLETE',
    'ADD_COMMENT_USER_START',
    'ADD_COMMENT_USER_COMPLETE',
    'SELECT_USERS',
    'REMOVE_USER_START',
    'REMOVE_USER_COMPLETE',
    'CLEAR_USER_SELECTION',

    'FETCH_SUPPLIERS_START',
    'FETCH_SUPPLIERS_COMPLETE',
    'FETCH_FEED_START',
    'FETCH_FEED_COMPLETE',

    'FETCH_PRODUCTCATEGORIES_START',
    'FETCH_PRODUCTCATEGORIES_COMPLETE',
    'FETCH_PRODUCTS_START',
    'FETCH_PRODUCTS_COMPLETE',
    'FETCH_PRODUCT_START',
    'FETCH_PRODUCT_COMPLETE',
    'UPDATE_PRODUCT_START',
    'UPDATE_PRODUCT_COMPLETE',
    'CREATE_PRODUCT_START',
    'CREATE_PRODUCT_COMPLETE',
    'CREATE_PRODUCT_CONFLICT',
    'ADD_PRODUCT_FILE_START',
    'ADD_PRODUCT_FILE_COMPLETE',

    'FETCH_MAILTEMPLATES_START',
    'FETCH_MAILTEMPLATES_COMPLETE',
    'SEND_MAILTEMPLATE_START',
    'SEND_MAILTEMPLATE_COMPLETE',
    'SEND_MAILTEMPLATE_RESET',

    'SOCKET_CONNECTED',
    'SOCKET_AUTHENTICATED',
    'SOCKET_JOIN_INQUIRY',
    'SOCKET_UPDATE_INQUIRY',
    'JOIN_USER_SUCCESS',

    'FETCH_REPORT_START',
    'FETCH_REPORT_COMPLETE',

    'FETCH_FILES_START',
    'FETCH_FILES_COMPLETE',
    'FETCH_FILES_FAILED',
    'CHANGE_PROJECT',
    'CHANGE_PROJECT_FAILED',
    'REMOVE_FILE_START',
    'REMOVE_FILE_COMPLETE',
    'REMOVE_FILE_FAILED',

    'UPLOAD_START',
    'UPLOAD_COMPLETE',
    'UPLOAD_FAILED',
  ),
  APP: 'carrefour',
  API: getAPI(),
  SOCKET: getAPI(),
  DEFAULT_PROJECT: 'jonas',

}
