export { default as application } from './application'
export { default as inquiries } from './inquiries'
export { default as files } from './files'
export { default as products } from './products'
export { default as users } from './users'
export { default as notifications } from './notifications'
export { default as mailTemplates } from './mailtemplates'
